// بيانات مزوّدي الخدمة
final List<Map<String, dynamic>> providers = [
  {
    'serviceId': 1,
    'name': 'Salma Mustafa',
    'location': 'Aleppo',
    'hourlyRate': 20,
    'experience': 3,
    'image': 'assets/images/provider2.png',
    'gallery': ['assets/images/work1.png', 'assets/images/work2.png'],
    'bio': 'Experienced cleaner with 3 years of work.',
    'availableStart': DateTime(2025, 4, 22),
    'availableEnd': DateTime(2025, 4, 26),
  },
  {
    'serviceId': 2,
    'name': 'Mohammed Ali',
    'location': 'Damascus',
    'hourlyRate': 30,
    'experience': 5,
    'image': 'assets/images/provider1.png',
    'gallery': ['assets/images/work3.png', 'assets/images/work1.png'],
    'bio': 'Painter with over 5 years of experience.',
    'availableStart': DateTime(2025, 4, 24),
    'availableEnd': DateTime(2025, 4, 28),
  },
  {
    'serviceId': 1,
    'name': 'Lina Ibrahim',
    'location': 'Aleppo',
    'hourlyRate': 15,
    'experience': 1,
    'image': 'assets/images/provider1.png',
    'gallery': ['assets/images/work2.png'],
    'bio': 'New but skilled cleaner.',
    'availableStart': DateTime(2025, 4, 23),
    'availableEnd': DateTime(2025, 4, 25),
  },
  {
    'serviceId': 5,
    'name': 'Ahmad Taha',
    'location': 'Homs',
    'hourlyRate': 45,
    'experience': 10,
    'image': 'assets/images/provider1.png',
    'gallery': ['assets/images/work4.png'],
    'bio': 'Professional carpenter for over 10 years.',
    'availableStart': DateTime(2025, 4, 23),
    'availableEnd': DateTime(2025, 4, 28),
  },
  {
    'serviceId': 3,
    'name': 'Ahmad Taha',
    'location': 'Homs',
    'hourlyRate': 45,
    'experience': 10,
    'image': 'assets/images/provider2.png',
    'gallery': ['assets/images/work4.png'],
    'bio': 'Professional carpenter for over 10 years.',
    'availableStart': DateTime(2025, 4, 23),
    'availableEnd': DateTime(2025, 4, 28),
  },
  {
    'serviceId': 2,
    'name': 'Ahmad Taha',
    'location': 'Homs',
    'hourlyRate': 45,
    'experience': 10,
    'image': 'assets/images/provider1.png',
    'gallery': ['assets/images/work4.png'],
    'bio': 'Professional carpenter for over 10 years.',
    'availableStart': DateTime(2025, 4, 23),
    'availableEnd': DateTime(2025, 4, 28),
  },
  {
    'serviceId': 4,
    'name': 'Ahmad Taha',
    'location': 'Homs',
    'hourlyRate': 45,
    'experience': 10,
    'image': 'assets/images/provider1.png',
    'gallery': ['assets/images/work4.png'],
    'bio': 'Professional carpenter for over 10 years.',
    'availableStart': DateTime(2025, 4, 23),
    'availableEnd': DateTime(2025, 4, 28),
  },
  {
    'serviceId': 5,
    'name': 'Ahmad Taha',
    'location': 'Homs',
    'hourlyRate': 45,
    'experience': 10,
    'image': 'assets/images/provider2.png',
    'gallery': ['assets/images/work4.png'],
    'bio': 'Professional carpenter for over 10 years.',
    'availableStart': DateTime(2025, 4, 23),
    'availableEnd': DateTime(2025, 4, 28),
  },
  {
    'serviceId': 4,
    'name': 'Ahmad Taha',
    'location': 'Homs',
    'hourlyRate': 45,
    'experience': 10,
    'image': 'assets/images/provider2.png',
    'gallery': ['assets/images/work4.png'],
    'bio': 'Professional carpenter for over 10 years.',
    'availableStart': DateTime(2025, 4, 23),
    'availableEnd': DateTime(2025, 4, 28),
  },
];
